### ISSUE TITLE
Ryzen 3700x optimized x265?  Which one should I use?

### ISSUE THREAD

**Issue by Neltulz** [DJATOM/x265-aMod#11]
I notice there's x265...znver1.exe and x265...znver2.exe

Are these ryzen optimized builds?  If so, which one should I use for a Ryzen 3700x?

**Comment by DJATOM** [comment]
Zen, Zen+ - znver1
Zen2 - znver2
Zen3 - will be supported with next gcc version, use znver2 for now

**Comment by Neltulz** [comment]
Thanks!
