### ISSUE TITLE
Dolby Vision support

### ISSUE THREAD

**Issue by kliffgomel** [DJATOM/x265-aMod#12]
The --dolby-vision-rpu and --dolby-vision-profile options may not work ...

[LA_A006_C008_4K_HDR_HEVC_staxrip.log](https://github.com/DJATOM/x265-aMod/files/6061002/LA_A006_C008_4K_HDR_HEVC_staxrip.log)

**Comment by DJATOM** [comment]
> x265 [info]: HEVC encoder version 3.5_RC1+2+23-bd060601e [Mod by Patman]

Are sure you reported at right place?

**Comment by kliffgomel** [comment]
yes, probably wrong ..
did not notice that the mod was replaced again
sorry

**Comment by DJATOM** [comment]
No problem. Probably my builds will work with those options, I just never encoded HDR content on my own, so I'm not aware.
