### ISSUE TITLE
performance difference between toolchain

### ISSUE THREAD

**Issue by yukkohzq** [DJATOM/x265-aMod#13]
Sorry for bothering
but I am wondering if there is any performance difference between LLVM and GCC on new architect like znver3 ?

**Comment by DJATOM** [comment]
I'm with 3900x, can't measure that.

**Comment by yukkohzq** [comment]
Sir, can you provide your build scripts?
Just for reference, I don't know how to deal with optimize flags.
big thanks

**Comment by DJATOM** [comment]
I just committed them.
