### ISSUE TITLE
Request for AviSynth support

### ISSUE THREAD

**Issue by stax76** [DJATOM/x265-aMod#2]
I would like to request AviSynth support, direct support without lavf.

https://github.com/msg7086/x265-Yuuki-Asuna

https://github.com/msg7086/x265-Yuuki-Asuna/issues/11

**Comment by DJATOM** [comment]
I'm quite busy with my working stuff right now, will consider it in the future.

**Comment by stax76** [comment]
OK, thanks for considering.

**Comment by DJATOM** [comment]
Implemented in 21b681a420e729740753c92bff12424ce6a35793.
