### ISSUE TITLE
IS "OPT-BDVER1" FOR BROADWELL ?

### ISSUE THREAD

**Issue by katyurua** [DJATOM/x265-aMod#29]
IS "OPT-BDVER1" FOR BROADWELL ?
```
x265-x64-v3.6+30-aMod-gcc13.2.0-opt-bdver1.exe
```

**Comment by DJATOM** [comment]
No, that's for AMD's Bulldozer CPUs.

**Comment by katyurua** [comment]
> No, that's for AMD's Bulldozer CPUs.

ANY CHANCE TO GET BROADWELL OPT  VERSION IN FUTURE ？ 
OR ANY ALTERNATIVES WORKS FOR BROADWELL？

**Comment by DJATOM** [comment]
Haswell / Skylake should be most compatible builds.

**Comment by katyurua** [comment]
> Haswell / Skylake should be most compatible builds.

GOT IT. THANKS
