### ISSUE TITLE
Enable --dhdr10-info option

### ISSUE THREAD

**Issue by kliffgomel** [DJATOM/x265-aMod#5]
Please enable --dhdr10-info support when compiling the codec.
x265 [info]: HEVC encoder version 3.4+62-5b977e9ed [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: --dhdr10-info disabled. Enable HDR10_PLUS in cmake.

**Comment by DJATOM** [comment]
With later builds then.

**Comment by DJATOM** [comment]
https://github.com/staxrip/staxrip/issues/464#issuecomment-763819976 hope it works
