### ISSUE TITLE
--limit-refs default value for Medium preset

### ISSUE THREAD

**Issue by Dendraspis** [DJATOM/x265-aMod#6]
Hello,

since your build is the only one compatible with StaxRip at the time, so that it can't be exchanged, I would like to ask, if you want to fix a bug in x265, that exists for a very long time. 
Personally I don't care, because I know this bug and I always use the ***Slow*** preset, but maybe you wanna fix it though.

According to the [Preset table](https://x265.readthedocs.io/en/master/presets.html) and [parameter description](https://x265.readthedocs.io/en/master/cli.html#cmdoption-limit-refs) `--limit-refs`'s default value should be `3`, but for ***Medium*** preset it is set to `1`.
I created an [issue](https://bitbucket.org/multicoreware/x265_git/issues/566/limit-refs-at-medium-preset), but nothing happens.  Then I created a [pull request](https://bitbucket.org/multicoreware/x265_git/pull-requests/4), but again nothing happens and I doubt, that something will happen.

 😁  So it's up to you...

**Comment by DJATOM** [comment]
Sure. You can propose your PR here. I just finished to clean my PC and will go to bed soon.

**Comment by Dendraspis** [comment]
That was quick.  😎
Looks like you can't find your bed.  😜

Thanks.

**Comment by DJATOM** [comment]
I decided to drink some tea beforehand 😊
